### PR TITLE
Update to 1.20

### PR DESCRIPTION
**Pull request by NotNite**
First time using this mod, wanted to use it for 1.20, realized there wasn't an update, chimpanzee brain have idea and 30 minutes after blacking out in a cold sweat with IntelliJ open I have a draft PR.

Some notes:

- **I can't actually test this right now** - it starts and gets to the main menu, but Mojang removed the multiplayer server CLI arg, so I'd need to make my own mod to see if it works
- Because of the new a11y onboarding screen, you need `onboardAccessibility:false` in options.txt to not immediately softlock while the soothing voice of the narrator reads out `accessibility.onboarding.screen.narrator`
- Had to remove `rootProject.name = "Curium"` from settings.gradle because I cloned it as `curium` and something something case sensitivity
- `Window::readIconPixels` is just gone. I did not have enough foresight to also set up a dev env in 1.19.4, so I have no idea what it's supposed to do or where it gets called. Removing the Overwrite just seemed to work (lol)
-  I strongly suspect more things will be broken from GuiGraphics. I don't see any errors in my IDE but who knows!
- My game crashes with Fabric API installed and I have no idea why, `GameRenderer::render` conflicting being one of them. I tried commenting it out to get it to work, and the game Didn't Crash, but there was another conflict with sound that I didn't want to go track down

### CODE REVIEW

**Comment by ghost** [comment]
Hey, thanks for submitting this PR.

Some replies to your notes:
- You can mixin at the end of `main` (maybe `Minecraft#<init>`?) to force join a server. Look at wherever 1.19.4 puts it, I suppose. I didn't actually realize they had removed this. I would suggest adding a system property (similar to the current ASM debug one) named something like `curium.debug.server` and `curium.debug.port` that mimics the old behaviour if possible.
- It would probably be best to force it to always fail instead of modifying `options.txt`, i.e. just `@Redirect` on the field access or the `setScreen` call. I'm not actually sure if the narrator causes any issues in general, might have to hack that out.
- That's fine
- Minecraft tends to change stuff like that across versions. Just removing the injects or such is fine as long as LWJGL is still not loaded (I can check this or explain how to if you need me to)
- If it doesn't crash by the title screen it is _generally_ doing okay as long as level rendering doesn't crash
- Fabric API is not compatible for various reasons, doesn't work on 1.19.4 or prior versions either. I ought to fix it - I wouldn't worry about changing it right now.

You also have my Discord if you want help with anything :)

**Comment by NotNite** [comment]
The last few commits I pushed gets everything working - the world would randomly stop ticking which I managed to trace to an infinite loop in a method in Frustum. It also seems to work with Fabric API now, too, and I was able to get a simple bot working with [portablemc](https://github.com/mindstorm38/portablemc).

I'll take the PR off draft because it Technically Works:tm:.

**Comment by katietheqt** [comment]
Seems like `com.mojang.blaze3d.audio.OggAudioStream` changed slightly and loads LWJGL now

**Comment by NotNite** [comment]
...Oops. I'm not sure I have time for most of today to fix it, but I'll get to it later if I can.

**Comment by katietheqt** [comment]
I can fix it if you like, or I can explain how you can check what loads stuff

**Comment by NotNite** [comment]
It'd probably be better for you to fix right now. You should be able to commit to the fork.

**Comment by katietheqt** [comment]
Alright, I believe that's everything. Thanks for the PR :)

**Pull request merged**
